### ISSUE TITLE
Since this is github, no project would be complete without at least one issue filed against it!

### ISSUE THREAD

**Issue by jordanhubbard** [jvns/tiny-resolver#2]
`go run resolve.go www.shitpile.com`
Hilarity ensues.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x100fa26e0]

goroutine 1 [running]:
main.getAnswer(0x0)
	/Users/jkh/Src/gocode/tiny-resolver/resolve.go:35 +0x20
main.resolve({0x140001520a8, 0x11})
	/Users/jkh/Src/gocode/tiny-resolver/resolve.go:17 +0x84
main.main()
	/Users/jkh/Src/gocode/tiny-resolver/resolve.go:78 +0xc4
exit status 2

```
Please do not ask how I happened to think up or choose that test domain name.   I do not know, it just came to me at random.  Perhaps I was thinking of an old car I used to own. It is nonetheless a unique finding.

**Comment by bortzmeyer** [comment]
This is probably because the tiny resolver don't have specific code for aliases (www.shitpile.com is an alias to the canonical name traff-3.hugedomains.com). Therefore, it does not stop (there are NS in the authority section), thinking the answer must be later, until it runs out of resources.

Two lessons here: a resolver must always have limits on the number of iterations to resolve a name (think of loops!) and the tiny resolver is tiny, it was not designed to handle all the complicated cases of the real DNS.
